import { httpRouter } from 'convex/server';
import JSZip from 'jszip';
import { internal } from './_generated/api';
import type { Id } from './_generated/dataModel';
import { httpAction } from './_generated/server';

const http = httpRouter();

/**
 * GET /api/runs/:id/zip
 *
 * Returns the latest ui_kit for the run as a downloadable ZIP. Includes a
 * HANDOFF.md file with integration instructions for Claude Code / Cursor /
 * Windsurf so the bundle is self-explanatory.
 *
 * 404 if the run doesn't exist or no ui_kit has been produced yet.
 *
 * Note: this lives in convex/http.ts (Node runtime) because JSZip's
 * generateAsync('nodebuffer') needs the Node Buffer API. The other queries
 * in this repo can stay in the default V8 runtime.
 */
http.route({
  pathPrefix: '/api/runs/',
  method: 'GET',
  handler: httpAction(async (ctx, req) => {
    const url = new URL(req.url);

    // /api/runs/:id/source — serve the gpt-image-2 source mockup as PNG
    const sourceMatch = url.pathname.match(/^\/api\/runs\/([a-z0-9_]+)\/source$/i);
    if (sourceMatch !== null && sourceMatch[1] !== undefined) {
      const runId = sourceMatch[1] as Id<'runs'>;
      const run = await ctx.runQuery(internal.runs.getInternal, { runId });
      if (run === null || run.sourceImageStorageId === undefined) {
        return new Response(JSON.stringify({ error: 'no_source_image' }), {
          status: 404,
          headers: { 'content-type': 'application/json' },
        });
      }
      const blob = await ctx.storage.get(run.sourceImageStorageId);
      if (blob === null) {
        return new Response(JSON.stringify({ error: 'storage_miss' }), {
          status: 404,
          headers: { 'content-type': 'application/json' },
        });
      }
      return new Response(blob, {
        status: 200,
        headers: {
          'content-type': 'image/png',
          'cache-control': 'private, max-age=300',
        },
      });
    }

    // /api/runs/:id/zip — pack the latest ui_kit + return as a ZIP
    const m = url.pathname.match(/^\/api\/runs\/([a-z0-9_]+)\/zip$/i);
    if (m === null || m[1] === undefined) {
      return new Response(JSON.stringify({ error: 'not_found' }), {
        status: 404,
        headers: { 'content-type': 'application/json' },
      });
    }
    const runId = m[1] as Id<'runs'>;

    const uiKit = await ctx.runQuery(internal.uiKits.getLatestInternal, { runId });
    if (uiKit === null) {
      return new Response(JSON.stringify({ error: 'no_ui_kit_yet' }), {
        status: 404,
        headers: { 'content-type': 'application/json' },
      });
    }
    const run = await ctx.runQuery(internal.runs.getInternal, { runId });
    const parity = await ctx.runQuery(internal.parityReports.getLatestInternal, { runId });

    const zip = new JSZip();
    const files = uiKit.files as Record<string, string>;
    for (const [path, content] of Object.entries(files)) {
      zip.file(path, content);
    }

    const handoff = `# ${uiKit.slug} — handoff

Generated by parity-studio run ${String(runId)}.

Source prompt: ${run?.prompt ?? '(image-only)'}
Final parity:  ${
      parity && parity.totalChecks > 0
        ? `${(parity.passCount / parity.totalChecks).toFixed(2)} (${parity.passCount}/${parity.totalChecks} ${parity.status})`
        : 'n/a'
    }
Total cost:    $${((run?.costMicroUsd ?? 0) / 1_000_000).toFixed(4)}
Iterations:    ${run?.iterationsCompleted ?? 0}

## Integrate with Claude Code / Cursor / Windsurf

Unzip into your repo at the path of your choice. Then ask your coding agent:

> Integrate the ui_kits/${uiKit.slug}/ folder into the existing app at <your route>.
> Use components/*.tsx as the building blocks. Wire tokens.css into your global stylesheet.
> Preserve all visible text and numbers verbatim — they came from the source mockup.

Verify visually before merging. If parity drifted from your render, run
parity_verify (via parity-studio-mcp) with the integrated render to surface gaps.

manifest.json schemaVersion 1 contract is stable across minor versions.
`;
    zip.file(`ui_kits/${uiKit.slug}/HANDOFF.md`, handoff);

    // V8 runtime: use 'arraybuffer' since Convex's Response typing prefers
    // ArrayBuffer/string over Uint8Array (which carries an ArrayBufferLike
    // generic that doesn't satisfy BodyInit in the strict path).
    const buf = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' });
    return new Response(buf, {
      status: 200,
      headers: {
        'content-type': 'application/zip',
        'content-disposition': `attachment; filename="${uiKit.slug}.zip"`,
        'cache-control': 'private, no-store',
      },
    });
  }),
});

export default http;
