/**
 * Local dashboard HTTP server. Hono on @hono/node-server. Auto-launched
 * by the MCP server on first tool invocation (or eagerly via env flag).
 *
 * Routes:
 *   GET  /                   single-file static dashboard
 *   GET  /events             SSE stream of run state updates
 *   GET  /api/runs           list of recent runs
 *   GET  /api/runs/:id       full state of one run
 *   GET  /api/runs/:id/zip   download the latest ui_kit as a ZIP
 *   GET  /api/health         { ok: true, runCount, subscriberCount }
 *
 * Port resolution: tries PARITY_DASHBOARD_PORT (default 6280), falls back
 * to a random free port if taken. Returns the actual URL.
 *
 * BOUND rule: max 64 concurrent SSE subscribers; older ones get dropped.
 */

import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import JSZip from 'jszip';
import { eventBus } from './events.js';
import { renderDashboardHtml } from './staticHtml.js';

const DEFAULT_PORT = Number(process.env['PARITY_DASHBOARD_PORT'] ?? 6280);
const MAX_SUBSCRIBERS = 64;

interface DashboardServerHandle {
  url: string;
  port: number;
  shutdown: () => Promise<void>;
}

let handle: DashboardServerHandle | null = null;
let starting: Promise<DashboardServerHandle> | null = null;

export async function ensureDashboard(): Promise<DashboardServerHandle> {
  if (handle !== null) return handle;
  if (starting !== null) return starting;
  starting = startDashboard();
  try {
    handle = await starting;
    return handle;
  } finally {
    starting = null;
  }
}

export function getDashboardUrl(): string | null {
  return handle?.url ?? null;
}

async function startDashboard(): Promise<DashboardServerHandle> {
  const app = new Hono();

  app.get('/', (c) => {
    return c.html(renderDashboardHtml());
  });

  app.get('/api/health', (c) => {
    return c.json({
      ok: true,
      runCount: eventBus.listRuns().length,
      subscriberCount: eventBus.subscriberCount(),
    });
  });

  app.get('/api/runs', (c) => {
    return c.json({
      runs: eventBus.listRuns().map(stripHeavy),
    });
  });

  app.get('/api/runs/:id', (c) => {
    const id = c.req.param('id');
    const run = eventBus.getRun(id);
    if (run === undefined) return c.json({ error: 'not_found' }, 404);
    return c.json(stripHeavy(run));
  });

  app.get('/api/runs/:id/zip', async (c) => {
    const id = c.req.param('id');
    const run = eventBus.getRun(id);
    if (run === undefined || !run.uiKitFiles || !run.uiKitSlug) {
      return c.json({ error: 'no_ui_kit_yet' }, 404);
    }
    const zip = new JSZip();
    for (const [path, content] of Object.entries(run.uiKitFiles)) {
      zip.file(path, content);
    }
    zip.file(
      `ui_kits/${run.uiKitSlug}/HANDOFF.md`,
      `# ${run.uiKitSlug} — handoff

Generated by parity-studio-mcp run ${id}.
Source prompt: ${run.prompt ?? '(image-only)'}
Final parity: ${run.parityReport?.parityScore?.toFixed(2) ?? 'n/a'} (${run.parityReport?.status ?? 'n/a'})
Total cost: $${run.costUsd.toFixed(4)}
`,
    );
    const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
    return new Response(buf, {
      status: 200,
      headers: {
        'content-type': 'application/zip',
        'content-disposition': `attachment; filename="${run.uiKitSlug}.zip"`,
      },
    });
  });

  app.get('/events', (c) => {
    if (eventBus.subscriberCount() >= MAX_SUBSCRIBERS) {
      return c.json({ error: 'too_many_subscribers' }, 503);
    }
    const stream = new ReadableStream({
      start(controller) {
        const enc = new TextEncoder();
        const send = (chunk: string) => {
          try {
            controller.enqueue(enc.encode(chunk));
          } catch {
            unsubscribe();
          }
        };
        // Hello message so the client knows it's connected
        send(`event: hello\ndata: ${JSON.stringify({ ts: Date.now() })}\n\n`);
        const unsubscribe = eventBus.subscribe(send);
        // Heartbeat every 25s so reverse proxies don't kill idle SSE
        const interval = setInterval(() => send(': heartbeat\n\n'), 25_000);
        c.req.raw.signal.addEventListener('abort', () => {
          clearInterval(interval);
          unsubscribe();
          try {
            controller.close();
          } catch {
            /* already closed */
          }
        });
      },
    });
    return new Response(stream, {
      headers: {
        'content-type': 'text/event-stream',
        'cache-control': 'no-cache, no-transform',
        connection: 'keep-alive',
        'x-accel-buffering': 'no',
      },
    });
  });

  // Try DEFAULT_PORT, fall back to OS-assigned (port 0)
  let server: ReturnType<typeof serve> | null = null;
  let actualPort = DEFAULT_PORT;
  try {
    server = await listenOnPort(app, DEFAULT_PORT);
  } catch {
    server = await listenOnPort(app, 0);
    // Hono's serve doesn't expose the resolved port directly; we need to read
    // it from the underlying http server.
    const addr = (server as unknown as { address: () => { port: number } }).address?.();
    actualPort = addr?.port ?? DEFAULT_PORT;
  }

  const url = `http://127.0.0.1:${actualPort}`;
  const localHandle: DashboardServerHandle = {
    url,
    port: actualPort,
    shutdown: async () => {
      if (server === null) return;
      await new Promise<void>((resolve) => {
        (server as unknown as { close: (cb: () => void) => void }).close(() => resolve());
      });
      handle = null;
    },
  };
  return localHandle;
}

async function listenOnPort(app: Hono, port: number): Promise<ReturnType<typeof serve>> {
  return await new Promise((resolve, reject) => {
    let s: ReturnType<typeof serve> | null = null;
    s = serve(
      {
        fetch: app.fetch,
        port,
        hostname: '127.0.0.1',
      },
      (info) => {
        // info.port is the resolved port (matters when port=0)
        if (s !== null) {
          // Stash actual port on the server object for reading later
          (s as unknown as { _resolvedPort: number })._resolvedPort = info.port;
          resolve(s);
        }
      },
    );
    s.on('error', (err: Error) => reject(err));
  });
}

/**
 * Drop big fields before sending over the SSE wire / REST list. The full
 * artifact + ui_kit files stay server-side and are only sent for the
 * specific run via /api/runs/:id and /api/runs/:id/zip.
 */
function stripHeavy(run: import('./events.js').RunRecord) {
  return {
    id: run.id,
    createdAt: run.createdAt,
    updatedAt: run.updatedAt,
    status: run.status,
    stages: run.stages,
    prompt: run.prompt,
    sourceImageBase64: run.sourceImageBase64,
    sourceImageMimeType: run.sourceImageMimeType,
    artifactHtmlPreview: run.artifactHtmlPreview,
    uiKitSlug: run.uiKitSlug,
    uiKitFileCount: run.uiKitFiles ? Object.keys(run.uiKitFiles).length : 0,
    uiKitFilePaths: run.uiKitFiles ? Object.keys(run.uiKitFiles) : [],
    parityReport: run.parityReport,
    costUsd: run.costUsd,
    latencies: run.latencies,
    modelsUsed: run.modelsUsed,
    log: run.log,
    errorMessage: run.errorMessage,
  };
}
